language: python

python:
  - "3.4"

services:
  - postgresql
addons:
    postgresql: "9.4"
env:
  - LASAGNA_SETTINGS_FILE="$TRAVIS_BUILD_DIR/lasagna/test/settings_travis.py"

before_install:
  - cd lasagna
install:
  - pip install -e .

before_script:
  - ../potato/travis.sh

script:
  - python setup.py coverage
  - python setup.py test
