language: python

python:
  - "3.4"

services:
  - postgresql
addons:
    postgresql: "9.4"
env:
  - LASAGNA_SETTINGS_FILE="$TRAVIS_BUILD_DIR/lasagna/tests/settings_travis.py"

before_install:
  - cd lasagna
install:
  - pip install -e .[tests]

before_script:
  - ../potato/travis.sh

script:
  - flake8 lasagna tests
  - py.test -v --tb=line
