version: "2"
services:
  db:
    ports:
        - "5432:5432"
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-DB
      args:
        - PASSWORD=${DB_PASSWORD}
  dbwatcher:
    volumes:
      - ./rulzurdb:/mnt/
    links:
      - db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-DBwatcher
      args:
        - PASSWORD=${DB_PASSWORD}
  api:
    volumes:
      - ./rulzurapi:/opt/rulzurapi
      - ./rulzurfront/dist:/opt/rulzurapi/src/api/base/static
    links:
      - db
    ports:
      - "5000:5000"
    command: /bin/bash
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-API
  front:
    volumes:
      - ./rulzurfront:/opt/rulzurfront
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-Front
