version: "2"
services:
  potato:
    ports:
        - "5432:5432"
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-potato
      args:
        - PASSWORD=${DB_PASSWORD}
  potatowatcher:
    volumes:
      - ./potato:/mnt/
    links:
      - potato
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-potato-watcher
      args:
        - PASSWORD=${DB_PASSWORD}
  lasagna:
    volumes:
      - ./lasagna:/opt/lasagna
      - ./dessert/dist:/opt/lasagna/lasagna/api/base/static
    links:
      - potato
    ports:
      - "5000:5000"
    command: /bin/bash
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-lasagna
  dessert:
    volumes:
      - ./dessert:/opt/dessert
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-dessert
