# DBwatcher
#
# VERSION               0.0.1

FROM       debian:testing
MAINTAINER Maxime Vidori <maxime.vidori@gmail.com>

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y postgresql-client postgresql-autodoc graphviz

ENV PGPASSFILE /tmp/.pgpass
ENV PGHOST db
ENV PGDATABASE rulzurdb
ENV PGUSER rulzurdb


ARG PASSWORD

RUN echo "*:*:${PGDATABASE}:${PGUSER}:${PASSWORD}" >  ${PGPASSFILE}
RUN echo "*:*:rulzurdb_test:${PGUSER}:${PASSWORD}" >> ${PGPASSFILE}
RUN echo "*:*:template1:${PGUSER}:${PASSWORD}"     >> ${PGPASSFILE}

RUN chmod 600 ${PGPASSFILE}

WORKDIR /mnt
