# lasagna
#
# VERSION               0.0.1

FROM       debian:testing
MAINTAINER Maxime Vidori <maxime.vidori@gmail.com>

RUN apt-get update && \
    apt-get install -y python3.4 python3-pip libpq-dev && \
    apt-get clean

ENV LC_ALL "C.UTF-8"
ENV LANG "C.UTF-8"

ENV PYTHONDONTWRITEBYTECODE 1
ENV WORKDIR /opt/lasagna

EXPOSE 5000

WORKDIR ${WORKDIR}

CMD ["/usr/bin/python3", "lasagna/app.py"]
